import Navbar from '@/components/Header/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Header/Sidebar';
import MobileNavigation from '@/components/Header/MobileNavigation';
import { ThemeProvider } from '@/components/Providers/theme-provider';
import StoreProvider from '@/components/Providers/StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import Protected from '@/components/Providers/Protected';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Toaster />
            {children}
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
